- numpy is a numerical python or number python

- Its very halpful for  all math operation

- Representation of eliments or number we can do following way

    - list
 
    - tuple
 
    - array
 
    - tensor
 
- list and tuple very base levle representation

- whenever if any one say **array** means we need to recall **numpy**

- whenever if any one say **tensor** means we need to recall **tensorflow and pytorch**

- numpy arrays are having shape and dimensions

- numpy arreys and tensors are similar in nature

- if we use cpu then the numpy is best

- if we use gpu then tensors are best   

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.4'

In [3]:
import sys

In [4]:
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [3]:
import pandas as pd
pd.__version__

'2.3.3'

# create an array

In [8]:
l=[1,2,3,4]
l

[1, 2, 3, 4]

In [9]:
np.array(l)

array([1, 2, 3, 4])

# why numpy arrays are famous

In [11]:
l1=[10,20,30,40]
l2=[100,200,300,400]
l3=[]
for i,j in zip(l1,l2):
    l3.append(i+j)
l3

[110, 220, 330, 440]

In [12]:
l=[i+j for i,j in zip(l1,l2)]
l

[110, 220, 330, 440]

In [13]:
arr1=np.array(l1)
arr2=np.array(l2)
arr1,arr2

(array([10, 20, 30, 40]), array([100, 200, 300, 400]))

In [14]:
arr1+arr2

array([110, 220, 330, 440])

In [15]:
arr1-arr2

array([ -90, -180, -270, -360])

In [16]:
arr1*arr2

array([ 1000,  4000,  9000, 16000])

In [17]:
arr1/arr2

array([0.1, 0.1, 0.1, 0.1])

# speed test

In [22]:
import time
start=time.time()
l1=list(range(1,1000000))
l2=list(range(1,1000000))
l=[i*j for i,j in zip(l1,l2)]
end=time.time()
print(f"time taken {end-start}")

time taken 0.3858065605163574


In [23]:
import time
start=time.time()
arr1=np.array(list(range(1,1000000)))
arr2=np.array(list(range(1,1000000)))
arr1*arr2
end=time.time()
print(f"time taken {end-start}")

time taken 0.3738439083099365


In [9]:
import time
start=time.time()
l1=list(range(1,100000000))
l2=list(range(1,100000000))
l=[i*j for i,j in zip(l1,l2)]
end=time.time()
print(f"time taken {end-start}")

time taken 131.4336714744568


In [10]:
import time
start=time.time()
arr1=np.array(list(range(1,100000000)))
arr2=np.array(list(range(1,100000000)))
arr1*arr2
end=time.time()
print(f"time taken {end-start}")

time taken 99.71972870826721


In [11]:
import time
start=time.time()
l1=list(range(1,100000000))
l2=list(range(1,100000000))
l3=[]
for i,j in zip(l1,l2):
    l3.append(i*j)
end=time.time()
print(f"time taken {end-start}")

time taken 254.60483074188232


In [1]:
# change only my name

In [2]:
a=10
b=20
c=a+b
c

30

In [3]:
# where you go

In [ ]:
# What are you doing