- min

- max

- mean

- mode

- median

- variance

- standard deviation

- covariance

- correlation

- z score

- min max scalar

In [1]:
import numpy as np
l=[0,1,2,3,4,5,6,7,8,9]
np.min(l)

np.int64(0)

In [2]:
np.max(l)

np.int64(9)

In [3]:
np.mean(l)

np.float64(4.5)

In [5]:
np.median(l)

np.float64(4.5)

In [4]:
np.mod(l,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [6]:
np.var(l)

np.float64(8.25)

In [7]:
np.std(l)

np.float64(2.8722813232690143)

In [8]:
np.cov(l)

array(9.16666667)

In [9]:
np.correlate(l,(2,2))

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34])

In [10]:
np.zeros(l)

array([], shape=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), dtype=float64)

In [11]:
np.min_scalar_type(l)

dtype('int64')

In [1]:
import numpy as np
l=[10,20,30,40,50,60,70,80,90,100]
arr1=np.array(l)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# mean

# formula
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD56VuJ3Gb19HZFvpeG9mHRO4hVJACVMfqBQ&amp;s" class="sFlh5c FyHeAf" alt="The formula of mean Mean = Average score = The sum of data value n =... |  Download Scientific Diagram" jsname="JuXqh" style="max-width: 299px; width: 299px; height: 131px; margin: 4.5px 0px;" data-ilt="1764070447987">

In [13]:
np.mean(arr1)

np.float64(55.0)

In [14]:
Sum=np.sum(arr1)
count=np.count_nonzero(arr1)
Sum/count

np.float64(55.0)

# median

In [15]:
np.median(arr1)

np.float64(55.0)

# variance

# formula
<img src="https://images.ctfassets.net/pdf29us7flmy/4UEXUFiVFUgsNA9fZOOQf2/b9e09d7447df4f0253a145ad853eb883/resized.png?w=720&amp;q=100&amp;fm=jpg" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 694px; height: 124px; margin: 8px 0px; width: 305px;" alt="Variance: Definition, Formula and Step-by-Step Examples | Indeed.com" jsname="kn3ccd">

In [16]:
np.var(arr1)

np.float64(825.0)

In [17]:
# step1 = xi means array
# step2 = xbar means mean of array
# step3 = cal xi-xbar in the from of array
#         arr2=arr1-mean
# step4 = square the of xi-xbar
#         arr3=square(arr2)
# step5 = nr=sum of square of xi-xbar
#         nr=sum(arr3)
# step6 = nr/count

In [18]:
print(arr1)
mean=np.mean(arr1)
print(mean)
arr2=arr1-mean
print(arr2)
arr3=np.square(arr2)
print(arr3)
arr4=np.sum(arr3)
print(arr4)
arr5=arr4/np.count_nonzero(arr1)
print(arr5)

[ 10  20  30  40  50  60  70  80  90 100]
55.0
[-45. -35. -25. -15.  -5.   5.  15.  25.  35.  45.]
[2025. 1225.  625.  225.   25.   25.  225.  625. 1225. 2025.]
8250.0
825.0


In [19]:
np.sum(np.square(arr1-np.mean(arr1)))/np.count_nonzero(arr1)

np.float64(825.0)

# std

<img style="display: block;-webkit-user-select: none;margin:none;background-color: hsl(0, 0%, 90%);transition: background-color 300ms; width:150px; height: 100px;" src="https://imgs.search.brave.com/mpzDWJ7FJChw9Mh3EBGiyOLtqNanB2-2XUo_D2-B_tA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/c3RhbmRhcmRkZXZp/YXRpb25jYWxjdWxh/dG9yLmlvL3N0b3Jh/Z2UvMjAyMy9KdW4v/RnJhbWUxN184MC5w/bmc">

In [9]:
arr2=arr1-np.mean(arr1)
print(arr2)
arr3=np.square(arr2)
print(arr3)
arr4=np.sum(arr3)
print(arr4)
arr5=np.count_nonzero(arr1)
arr6=arr4/arr5
print(arr6)
arr7=np.sqrt(arr6)
print(round(arr7,2))

[-45. -35. -25. -15.  -5.   5.  15.  25.  35.  45.]
[2025. 1225.  625.  225.   25.   25.  225.  625. 1225. 2025.]
8250.0
825.0
28.72


In [10]:
count=np.count_nonzero(l)
std=np.sqrt(np.sum(np.square(arr1-np.mean(arr1)))/count)
print(round(std,2))

28.72


In [11]:
print(round(np.std(l),2))

28.72


# covariance

# formula
<img src="https://www.alchemer.com/wp-content/uploads/2019/04/covariance-formula-surveygizmo-blog.png" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 594px; height: 151px; margin: 0px; width: 304px;" alt="Understanding Variance, Covariance &amp; Correlation" jsname="kn3ccd">

In [12]:
x=range(1,11)
y=range(100,110)
len(x),len(y)

(10, 10)

In [24]:
list(x),list(y)

([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [25]:
arr1=np.array(x)
meanx=np.mean(arr1)
arr11=arr1-meanx
arr2=np.array(y)
meany=np.mean(arr2)
arr22=arr2-meany

arr3=arr11*arr22
arr4=np.sum(arr3)
arr4/(np.count_nonzero(arr1)-1)

np.float64(9.166666666666666)

In [26]:
arr1=np.array(x)
arr2=np.array(y)
np.sum((np.array(x)-np.mean(np.array(x)))*(np.array(y)-np.mean(np.array(y))))/(np.count_nonzero(arr1)-1)

np.float64(9.166666666666666)

In [13]:
np.cov(x,y)

array([[9.16666667, 9.16666667],
       [9.16666667, 9.16666667]])

# correlation coeffcient

<img style="display: block;-webkit-user-select: none;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://imgs.search.brave.com/TTscP02KLdjYjrFp3hzbYy3iqkcpjmBSneHLveUymRE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4x/LmJ5anVzLmNvbS93/cC1jb250ZW50L3Vw/bG9hZHMvMjAxOS8w/OS9QZWFyc29uLUNv/ZWZmaWNpZW50LWZv/cm11bGEucG5n" width="400" height="73">

In [27]:
arr1=np.array(x)
meanx=np.mean(arr1)
arr11=arr1-meanx
arr2=np.array(y)
meany=np.mean(arr2)
arr22=arr2-meany
arr3=arr11*arr22
NR=np.sum(arr3)
a=np.sum(np.square(arr11))
b=np.sum(np.square(arr22))
DR=np.sqrt(a*b)
NR/DR

np.float64(1.0)

# Euclidian Distance

<img style="display: block;-webkit-user-select: none;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://imgs.search.brave.com/S2YpzULhZG48JoO0KnNdxzLV5hsmFjpxvaLib_D1QyU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tYXRo/bW9ua3MuY29tL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA1/LzNELURpc3RhbmNl/LUZvcm11bGEuanBn" width="400" height="248">

In [28]:
x=(10,20)
y=(5,6)
arr1=np.array(x)
arr2=np.array(y)
np.sqrt(np.sum(np.square(arr1-arr2)))

np.float64(14.866068747318506)

In [29]:
from numpy.linalg import norm

In [30]:
x=(10,20)
y=(5,6)
arr1=np.array(x)
arr2=np.array(y)
norm(arr1-arr2)

np.float64(14.866068747318506)

# cosine similarity

<img style="display: block;-webkit-user-select: none;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://imgs.search.brave.com/uXlXldT93rjFwN38evQ7xnez12tyM9EMAZ04jtXNon0/rs:fit:0:180:1:0/g:ce/aHR0cHM6Ly9tZW1n/cmFwaC5jb20vaW1h/Z2VzL2Jsb2cvY29z/aW5lLXNpbWlsYXJp/dHktcHl0aG9uLXNj/aWtpdC1sZWFybi9j/b3NpbmUtc2ltaWxh/cml0eS1mb3JtdWxh/LWVxdWl2YWxlbnQu/cG5n" width="400" height="100">

In [31]:
x=[1,2,3]
y=[4,5,6]
# convert into array
# Nr =np.dot()
# dr=a*b
# a=norm(arr1)
arr1=np.array(x)
arr2=np.array(y)
Nr=np.dot(arr1,arr2)
norm_a=norm(arr1)
norm_b=norm(arr2)
Dr=norm_a*norm_b
Nr/Dr

np.float64(0.9746318461970762)

In [32]:
# mean
# median
# mode
# range
# mean deviation
# absolute mean deviation
# variance
# standard deviation
# kurtosis

In [33]:
X = [1, 2, 3, 4]
Y = [2, 4, 6, 8]
arr1=np.array(x)
arr2=np.array(y)
np.sum((np.array(x)-np.mean(np.array(x)))*(np.array(y)-np.mean(np.array(y))))/(np.count_nonzero(arr1))

np.float64(0.6666666666666666)

In [44]:
x = [1, 2, 3, 4]
y = [2, 4, 6, 8]
arr1=np.array(x)
arr2=np.array(y)
meanx=np.mean(arr1)
arr11=arr1-meanx
meany=np.mean(arr2)
arr22=arr2-meany
arr3=arr11*arr22
arr4=np.sum(arr3)
print(arr4)
arr4/4

10.0


np.float64(2.5)

In [ ]:
X = [10, 20, 30, 40]
Y = [12, 18, 28, 35]
arr1=np.array(x)