# 1D

In [1]:
import numpy as np
l1=[1,2,3,4]
arr1=np.array(l1)
arr1

array([1, 2, 3, 4])

In [6]:
arr1.ndim # number of dimensions

1

In [5]:
arr1.shape # number of raws and number of culumns

(4,)

In [4]:
arr1.size  # number of eliment

4

# 2D

In [4]:
l1=[10,20,30,40]
l2=[1,2,3,4]
# np.array(object,dtype)
arr1=np.array(l1)
arr2=np.array(l2)
np.array(arr1,arr2)   # l1=object l2=dtype

TypeError: Cannot construct a dtype from an array

In [9]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[l1,l2]
arr2=np.array(l)
arr2

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [10]:
print('shape:',arr2.shape)
print('size:',arr2.size)
print('dim:',arr2.ndim)

shape: (2, 4)
size: 8
dim: 2


# 3D

In [14]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=[100,200,300,400]
l=[[l1,l2,l3]]
arr3=np.array(l)
print(arr3)

[[[ 10  20  30  40]
  [  1   2   3   4]
  [100 200 300 400]]]


In [15]:
print('shape:',arr3.shape)
print('size:',arr3.size)
print('dim:',arr3.ndim)

shape: (1, 3, 4)
size: 12
dim: 3


# 4D

In [19]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=[100,200,300,400]
l4=['a','b','c','d']
l=[[[l1,l2,l3,l4]]]
arr4=np.array(l)
print(arr4)

[[[['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['100' '200' '300' '400']
   ['a' 'b' 'c' 'd']]]]


In [20]:
print('shape:',arr4.shape)
print('size:',arr4.size)
print('dim:',arr4.ndim)

shape: (1, 1, 4, 4)
size: 16
dim: 4


In [21]:
arr4[0,0,3,3]

'd'

In [2]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[l1,l2]
np.array(l)

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [3]:
np.array(l).shape
# there is a 4 values first=list
# l1=[1,2,3,4]
# l2=[1,2,3,4]
# l=[l1,l2]

(2, 4)

In [ ]:
3,2,3
m,n,k

k ====> number of elemnets in a list
        l=[1,2,3]
n ===> how many k's are repeasd 2
        A=[l,l]
m ===> how many times A repeated 3
        B=[A,A,A]

In [4]:
l=[1,2,3]
A=[l,l]
B=[A,A,A]
np.array(B).shape

(3, 2, 3)

In [ ]:
2,2,2,2
a,b,c,d

a =====>l=[10,20]
b =====>l1=[l,l]
c =====>l2=[l1,l1]
d =====>l3=[l2,l2]

In [5]:
l=[10,20]
l1=[l,l]
l2=[l1,l1]
l3=[l2,l2]
np.array(l3).shape

(2, 2, 2, 2)

In [10]:
2,4
l=[10,20,30,40]
l1=[l,l]
np.array(l1).shape

(2, 4)

In [36]:
# 3,3,4
# height, width, length
l=[10,20,30,40]
l1=['a','b','c','d']
l2=[1,2,3,4]
l3=[[l,l1,l2]]*3
np.array(l3).shape

(3, 3, 4)

In [33]:
l  = [10,20,30,40]
l1 = ['a','b','c','d']
l2 = [1,2,3,4]
l3 = [l, l1, l2]    # 3 lists, each of length 4

arr = [l3] * 3      # repeat 3 times → 3x3x4

np.array(arr).shape


(3, 3, 4)

In [39]:
4,3,2,2
l=[10,20]
l1=['a','b']
l2=[[l,l1]]*3
l3=[l2]*4
np.array(l3).shape

(4, 3, 2, 2)

In [47]:
5,4,3,2,1
l=[1]
l1=[l,l]
l2=[l1,l1,l1]
l3=[l2,l2,l2,l2]
l4=[l3,l3,l3,l3,l3]
np.array(l4).shape

(5, 4, 3, 2, 1)

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.random.rand(3,3)

array([[0.340195  , 0.04689357, 0.15726506],
       [0.89553852, 0.85580565, 0.0757451 ],
       [0.64608704, 0.19629603, 0.27054084]])

In [22]:
np.random.randint(1,10, size=(3,2))

array([[7, 7],
       [7, 3],
       [9, 1]], dtype=int32)

In [24]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr= np.array([1,2,3,4,5,6,7,8,9])
arr.reshape()